AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API/RELAY de consulta de hoteis

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  ViagensAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: demo.viagensapi.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/viagensaapi-0.0.1-SNAPSHOT.jar
      MemorySize: 2560
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  ViagensAPI:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/'
    Export:
      Name: ViagensApi

